# Generated by Django 3.1.3 on 2020-11-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0005_task_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='for_what',
            new_name='forwhat',
        ),
    ]
